# Generated by Django 4.2.7 on 2023-11-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Agencias de Viajes',
            },
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Personas con reservacion',
            },
        ),
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_De_Ingreso', models.DateField()),
                ('Fecha_De_Salida', models.DateField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.personas')),
                ('int', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.agencias')),
            ],
            options={
                'db_table': 'Reservas',
            },
        ),
    ]
