# Generated by Django 4.2.7 on 2023-11-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
                ('AñoDeConstruccion', models.DateField()),
                ('TiposDeHabitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
            options={
                'db_table': 'NOMBRE DEL HOTEL',
            },
        ),
    ]
