# Generated by Django 4.2.7 on 2023-11-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=2)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TiposDeHabitacion', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
                ('AñoDeConstruccion', models.DateField()),
                ('TiposDeHabitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.habitacion')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.categoria')),
            ],
            options={
                'db_table': 'NOMBRE DEL HOTEL',
            },
        ),
    ]
